### ISSUE TITLE
Tweak fastcgi buffers, just in case.

### ISSUE THREAD

**Issue by artmouse** [magenx/Magento-nginx-config#10]
fastcgi_max_temp_file_size 0;
fastcgi_buffer_size 128k;
fastcgi_buffers 256 4k;
fastcgi_busy_buffers_size 256k;
fastcgi_temp_file_write_size 256k;

**Comment by magenx** [comment]
you have to read this page `http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html`
and this page `https://gist.github.com/magnetikonline/11312172`to understand how to configure these buffers.
