### ISSUE TITLE
nginx: [emerg] duplicate listen options for 0.0.0.0:80 in /etc/nginx/port.conf:1

### ISSUE THREAD

**Issue by Morgy93** [magenx/Magento-nginx-config#11]
Hello,

I get the following error while trying to start nginx after using the [m1_config_install.sh:](https://github.com/magenx/Magento-nginx-config/blob/master/m1_config_install.sh)
`nginx: [emerg] duplicate listen options for 0.0.0.0:80 in /etc/nginx/port.conf:1`

- Ubuntu 16.04 xenial
- nginx/1.11.2 

I assume that it has something to do with the "reuseport" option, but I don't know how to resolve it other than removing it.

**Comment by uinique-ruud** [comment]
I also have it. Change line 1 of /etc/nginx/port.conf to:
listen 80;

**Comment by magenx** [comment]
yes, port.conf was included twice, actually removed this file. so main server block is` listen 80 reuseport;`
