### ISSUE TITLE
Unknown request_id variable

### ISSUE THREAD

**Issue by tmccaff** [magenx/Magento-nginx-config#18]
This is what I get trying to start nginx

unknown "request_id" variable

**Comment by magenx** [comment]
you need to upgrade your nginx version

**Comment by tmccaff** [comment]
I have nginx 1.10.2 so the newest release is 1.10.3? This will solve the problem?

**Comment by tmccaff** [comment]
Ok upgraded and still says unknown "request_id" variable is it supposed to be request or reguest?

**Comment by tmccaff** [comment]
I think I figured it out I need version 1.11

**Comment by magenx** [comment]
you dont have to write this question everywhere.

https://www.google.ie/webhp?q=nginx+request_id#safe=off&q=nginx+request_id
