### ISSUE TITLE
SSL update

### ISSUE THREAD

**Issue by grzegorz77** [magenx/Magento-nginx-config#20]
Hi,
You have written really great piece of code...thank you... i learn.... quite much ... but this Issue is to complex for me...still beyond my skills..
Could you pls update the part of manual? (magento2.1.5)
"for ssl configuration in nginx.conf you must:"?
I've done what you recommended but no success..
I can't bring nginx to SSL
I have tried many tricks ... Spent over 2 days about ::)
Could you help ?
edit: I can sent you access data to my test machine. Fresh dyployed.

**Comment by magenx** [comment]
its working after installation 
you just have to uncomment ssl parameters 

https://www.ssllabs.com/ssltest/analyze.html?d=

**Comment by grzegorz77** [comment]
Thank you very much... it was trivial from your point of view... 
/etc/nginx/nginx.conf
all SSL global settings are to uncomment (from ``ssl_session_cache`` up to ``resolver_timeout 5s;``)
(information for those like me in case when they stack on it)

PS: but believe ... there are areas (out of IT) where I am quite good at .. Thank you once more
PS2 You should open paid ticketing system for those like me :)

**Comment by magenx** [comment]
yes it was fixed (we uncommented all parameters) per your request

**Comment by grzegorz77** [comment]
I know... Thank you...
