### ISSUE TITLE
What happened to magenx.sh? 

### ISSUE THREAD

**Issue by ZayLong** [magenx/Magento-nginx-config#31]
is it deprecated or private now or what? It was quite useful.

**Comment by magenx** [comment]
it is only available as paid service

**Comment by ZayLong** [comment]
This?

https://www.magenx.com/shop/magenx-services/magento-2-server-installation-optimization/

**Comment by magenx** [comment]
this one as option, yes.

**Comment by ZayLong** [comment]
If I pay do I get the shell script?

**Comment by loopCM** [comment]
？

**Comment by magenx** [comment]
if you pay we can configure your server, you can create a snapshot,
then just change email address.
we can provide the configuration per project only.

**Comment by ZayLong** [comment]
ok thanks
