### ISSUE TITLE
Requests blocked from LinkedIn app on iOS

### ISSUE THREAD

**Issue by scottsb** [magenx/Magento-nginx-config#32]
The regex for bad user agents includes this line:

`~*(larbin|LeechFTP|Lightspeedsystems|litemage_walker|Link|LinksManager.com|Lipperhey|LinkpadBot|linkwalker|lwp-trivial|ltx71) 1;`

However, this also matches the user agent sent by requests from within the iOS LinkedIn app. For example:

`Mozilla/5.0 (iPad; CPU OS 12_4_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [LinkedInApp]`

The simple solution is to remove `|Link`, though I'm not sure if there's a better solution, as I don't know what agent that was intended to match in the first place.

**Comment by magenx** [comment]
regex can be updated as you like,
make it greedy or per exact word only.
this is only to make your access log less noisy.

**Comment by scottsb** [comment]
Of course it can be adjusted. But I thought it might be good to make the default not block users visiting from a major social media app. 🙂

**Comment by magenx** [comment]
default is obviously to block as many as you can. 
you have online business, not a 12yrsold beauty blog....

**Comment by scottsb** [comment]
Perhaps LinkedIn is not a major social network where you are from, so you are not familiar with it. It is a social network designed and used almost exclusively for business, so linking to a store (especially for B2B merchants) would be very normal. It's extremely popular in the United States: almost everyone in business is on it.
