### ISSUE TITLE
Varnish Configuration is not there

### ISSUE THREAD

**Issue by niteshorntech** [magenx/Magento-nginx-config#35]
I was checking your configuration and it looks good to me but i can not see the varnish configuration as well as how you are using SSL there.

**Comment by magenx** [comment]
https://github.com/magenx/Magento-nginx-config/blob/master/magento2/sites-available/magento2.conf#L46

**Comment by niteshorntech** [comment]
But i can not see any where the SSL certificate you used.

As well as i was talking about the varnish.conf and default.vcl file

**Comment by magenx** [comment]
https://github.com/magenx/Magento-nginx-config/blob/master/magento2/sites-available/magento2.conf#L40

https://devdocs.magento.com/guides/v2.3/config-guide/varnish/config-varnish-magento.html
