### ISSUE TITLE
limit_req_zone errors

### ISSUE THREAD

**Issue by jorgb90** [magenx/Magento-nginx-config#44]
Since the new NGINX config, zones are set with limit_req_zone settings, but this seems to give errors in the NGINX error.log:

[error] 1021727#1021727: *548591 limiting requests, excess: 4.061 by zone "customer", client: 127.0.0.1, server: 159.XX.XXX.72, request: "GET /customer/section/load/?sections=mst-gtm-addtocart&force_new_section_timestamp=false&_=1676993964847 HTTP/1.1"

It seems to be all normal requests. Should I higher the limits?

**Comment by jorgb90** [comment]
Its all coming from same client, server and zone.

**Comment by magenx** [comment]
make sure this /customer/section/load/ url not loading multiple times

**Comment by jorgb90** [comment]
isnt it more a problem that all requests come from one client? 127.0.0.1

**Comment by magenx** [comment]
check if real ip from configured correctly

**Comment by jorgb90** [comment]
that was it I guess. I needed to change to "real_ip_header CF-Connecting-IP;" in nginx.conf because of Cloudflare. I will monitor it now.
