### ISSUE TITLE
invalid parameter "if=$writelog"

### ISSUE THREAD

**Issue by Morgy93** [magenx/Magento-nginx-config#5]
While using default nginx install on Ubuntu 14.04 I'm running into the following error:

```
invalid parameter "if=$writelog" in /etc/nginx/sites-enabled/magento.conf:13
```

I assume that the map module is installed, because if you rely on this post http://askubuntu.com/a/556382 it should be included in the standard http modules.

Any clue?

**Comment by magenx** [comment]
nginx package in Ubuntu 14.04 is outdated, version 1.4.x missing many features and bugfixes.
 you have to install latest nginx package from official nginx repository ```http://nginx.org/en/linux_packages.html#mainline```

**Comment by Morgy93** [comment]
Alright, that's it.
Thanks for help!
